[project]
name = "cis-postgres"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psycopg[binary]>=3.2.9",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
